# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-12 13:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2019, 1, 12, 13, 8, 2, 602254, tzinfo=utc), verbose_name='date posted')),
                ('title', models.CharField(max_length=200)),
                ('text', models.CharField(max_length=1000)),
                ('author', models.CharField(max_length=100)),
            ],
        ),
    ]
