# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-12 13:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('billboard_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billboard',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 12, 13, 29, 20, 287067, tzinfo=utc), verbose_name='date posted'),
        ),
    ]
