# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-12 14:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('billboard_app', '0006_auto_20190112_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billboard',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 12, 14, 54, 13, 730082, tzinfo=utc), verbose_name='date posted'),
        ),
    ]
